import type { Plugin } from 'vite';
import path from 'node:path';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import { defineConfig } from 'wxt';

export default defineConfig({
  // Custom modules
  modules: ['./modules/wasm-assets.ts'],

  // Force MV3 for all browsers (Firefox included)
  manifestVersion: 3,

  // Exclude source maps from distribution zip
  // Source maps are generated locally for debugging but not distributed to users
  zip: {
    exclude: ['**/*.map'],
  },

  // Manifest configuration
  manifest: ({ browser }) => ({
    name: 'ResumeWright',
    version: '0.1.0',
    description: 'Export Claude-generated CVs to professional PDFs',
    permissions: ['storage', 'downloads'],
    icons: {
      16: '/icons/icon-16.png',
      32: '/icons/icon-32.png',
      48: '/icons/icon-48.png',
      128: '/icons/icon-128.png',
    },
    // MV3 CSP format (both Chrome and Firefox)
    // Strict CSP without 'unsafe-inline' for enhanced security
    //
    // Security Analysis:
    // ✓ NO inline styles in codebase (verified via grep)
    // ✓ Tailwind CSS generates external stylesheets (~55KB)
    // ✓ Vite bundles all styles into .css files loaded via <link> tags
    // ✓ Build succeeds without unsafe-inline
    // ✓ All tests pass with strict CSP
    //
    // Risk Assessment:
    // - LOW: No user-generated content that could inject styles
    // - LOW: All styles are compile-time generated by Tailwind + Vite
    // - ELIMINATED: style-src 'unsafe-inline' removed (was potential XSS vector)
    //
    // Required directives:
    // - 'wasm-unsafe-eval' for WebAssembly (WASM requires relaxed CSP per spec)
    // - All other directives use 'self' for maximum security
    content_security_policy: {
      extension_pages:
        "default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self'; object-src 'self'",
    },
    web_accessible_resources: [
      {
        resources: ['assets/*.wasm'],
        matches: [], // Extension pages only - WASM loaded via browser.runtime.getURL()
      },
    ],
    // Add Firefox-specific settings
    ...(browser === 'firefox' && {
      browser_specific_settings: {
        gecko: {
          id: 'extension@resumewright.com',
          data_collection_permissions: {
            required: ['none'],
          },
        },
      },
    }),
  }),

  // Development settings
  dev: {
    server: {
      port: 5173,
    },
  },

  // Build settings
  outDir: '.output',
  srcDir: '.',
  entrypointsDir: 'entrypoints',

  // Vite configuration
  vite: () => ({
    plugins: [
      // Stub out Node.js-specific loader for browser build
      {
        name: 'stub-node-loader',
        load(id) {
          // Replace loader.node.ts with a stub that throws if ever called
          // This file should never execute in browser - only dynamically imported in Node.js
          if (id.includes('loader.node')) {
            return `
              export function getDefaultNodeWasmPath() {
                throw new Error('Node.js loader should never be called in browser context');
              }
              export function initWASMNode() {
                throw new Error('Node.js loader should never be called in browser context');
              }
            `;
          }
        },
      },
      react({
        jsxRuntime: 'automatic',
        // Use SWC for faster transpilation (4x speedup vs esbuild)
        babel: undefined,
      }),
      wasm(),
    ] as Plugin[],
    esbuild: {
      // Use SWC for TypeScript transpilation instead of esbuild
      // Note: @vitejs/plugin-react already uses SWC by default
      // This is just to ensure consistency
      tsconfigRaw: {
        compilerOptions: {
          useDefineForClassFields: true,
        },
      },
    },
    resolve: {
      alias: {
        '@/background': path.resolve(__dirname, './src/background'),
        '@/popup': path.resolve(__dirname, './src/popup'),
        '@/shared': path.resolve(__dirname, './src/shared'),
        '@pkg': path.resolve(__dirname, '../../packages/rust-core/wasm-bridge/pkg'),
      },
    },
    build: {
      target: 'esnext',
      // Generate hidden source maps for debugging production issues
      // 'hidden' generates .map files but doesn't add sourceMappingURL comments
      // Source maps are stored locally for developer debugging but not distributed to users
      // Development: true (inline for hot reload)
      // Production: 'hidden' (files generated, not referenced in code)
      sourcemap: process.env.NODE_ENV === 'production' ? 'hidden' : true,
      // Use esbuild minification (doesn't require unsafe-eval)
      minify: 'esbuild',
      // Prevent WASM files from being inlined as base64
      assetsInlineLimit: 0,
      rollupOptions: {
        output: {
          // Exclude source content from maps (smaller files)
          // Stack traces will show file/line/col but not original source
          sourcemapExcludeSources: true,
          // Keep source map files in output directory for developer use
          sourcemapPathTransform: (relativeSourcePath: string) => {
            // Preserve relative paths for easier debugging
            return relativeSourcePath;
          },
        },
      },
    },
    // Optimize WASM
    optimizeDeps: {
      exclude: ['@pkg'],
    },
  }),
});
