// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const Dynamic: typeof import('solid-js/web').Dynamic
  const ErrorBoundary: typeof import('solid-js').ErrorBoundary
  const For: typeof import('solid-js').For
  const Index: typeof import('solid-js').Index
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const Match: typeof import('solid-js').Match
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const Portal: typeof import('solid-js/web').Portal
  const Show: typeof import('solid-js').Show
  const Suspense: typeof import('solid-js').Suspense
  const SuspenseList: typeof import('solid-js').SuspenseList
  const Switch: typeof import('solid-js').Switch
  const batch: typeof import('solid-js').batch
  const browser: typeof import('wxt/browser').browser
  const children: typeof import('solid-js').children
  const createContext: typeof import('solid-js').createContext
  const createDeferred: typeof import('solid-js').createDeferred
  const createEffect: typeof import('solid-js').createEffect
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createMemo: typeof import('solid-js').createMemo
  const createMutable: typeof import('solid-js/store').createMutable
  const createRenderEffect: typeof import('solid-js').createRenderEffect
  const createResource: typeof import('solid-js').createResource
  const createRoot: typeof import('solid-js').createRoot
  const createSelector: typeof import('solid-js').createSelector
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const createSignal: typeof import('solid-js').createSignal
  const createStore: typeof import('solid-js/store').createStore
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const hydrate: typeof import('solid-js/web').hydrate
  const indexArray: typeof import('solid-js').indexArray
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isServer: typeof import('solid-js/web').isServer
  const lazy: typeof import('solid-js').lazy
  const mapArray: typeof import('solid-js').mapArray
  const mergeProps: typeof import('solid-js').mergeProps
  const observable: typeof import('solid-js').observable
  const on: typeof import('solid-js').on
  const onCleanup: typeof import('solid-js').onCleanup
  const onError: typeof import('solid-js').onError
  const onMount: typeof import('solid-js').onMount
  const produce: typeof import('solid-js/store').produce
  const reconcile: typeof import('solid-js/store').reconcile
  const render: typeof import('solid-js/web').render
  const renderToStream: typeof import('solid-js/web').renderToStream
  const renderToString: typeof import('solid-js/web').renderToString
  const renderToStringAsync: typeof import('solid-js/web').renderToStringAsync
  const splitProps: typeof import('solid-js').splitProps
  const storage: typeof import('wxt/utils/storage').storage
  const untrack: typeof import('solid-js').untrack
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useContext: typeof import('solid-js').useContext
  const useTransition: typeof import('solid-js').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
