// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/converter.html"
    | "/help/error-recovery.md"
    | "/help/troubleshooting.md"
    | "/help/tsx-syntax-guide.md"
    | "/icons/icon-128.png"
    | "/icons/icon-128.svg"
    | "/icons/icon-16.png"
    | "/icons/icon-16.svg"
    | "/icons/icon-32.png"
    | "/icons/icon-48.png"
    | "/icons/icon-48.svg"
    | "/manifest.json"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
