#!/usr/bin/env bash
set -e

# ResumeWright Build Artifacts Cleanup Script
# Safely removes build artifacts and caches to reclaim disk space
# All removed files can be regenerated by running builds/tests

echo "🧹 ResumeWright Cleanup Script"
echo "=============================="
echo ""

# Function to show size before cleanup
show_size() {
    if [ -e "$1" ]; then
        du -sh "$1" 2>/dev/null || echo "0B"
    else
        echo "0B (not found)"
    fi
}

# Calculate total space before cleanup
echo "📊 Current Disk Usage:"
echo "  Root target/:              $(show_size target)"
echo "  Rust core target/:         $(show_size packages/rust-core/target)"
echo "  Documentation cache:       $(show_size .docs-cache)"
echo "  Test results:              $(show_size test-results)"
echo "  Playwright reports:        $(show_size playwright-report)"
echo "  Node modules (root):       $(show_size node_modules)"
echo ""

read -p "Continue with cleanup? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Cleanup cancelled"
    exit 0
fi

echo ""
echo "🗑️  Cleaning up..."
echo ""

# Clean Rust build artifacts
if [ -d "target" ]; then
    echo "  Cleaning root target/ directory..."
    cargo clean
    echo "    ✅ Root target/ cleaned"
else
    echo "    ⚠️  Root target/ not found, skipping"
fi

if [ -d "packages/rust-core/target" ]; then
    echo "  Cleaning packages/rust-core/target/ directory..."
    cd packages/rust-core && cargo clean && cd ../..
    echo "    ✅ Rust core target/ cleaned"
else
    echo "    ⚠️  packages/rust-core/target/ not found, skipping"
fi

# Clean documentation cache
if [ -d ".docs-cache" ]; then
    echo "  Removing .docs-cache/ directory..."
    rm -rf .docs-cache
    echo "    ✅ Documentation cache removed"
else
    echo "    ⚠️  .docs-cache/ not found, skipping"
fi

# Clean test artifacts
if [ -d "test-results" ]; then
    echo "  Removing test-results/ directory..."
    rm -rf test-results
    echo "    ✅ Test results removed"
else
    echo "    ⚠️  test-results/ not found, skipping"
fi

if [ -d "playwright-report" ]; then
    echo "  Removing playwright-report/ directory..."
    rm -rf playwright-report
    echo "    ✅ Playwright reports removed"
else
    echo "    ⚠️  playwright-report/ not found, skipping"
fi

echo ""
echo "✨ Cleanup complete!"
echo ""
echo "📝 Note: To rebuild the project, run:"
echo "  pnpm build        # Full build (WASM + extension)"
echo "  pnpm build:wasm   # WASM only"
echo "  pnpm test         # Regenerate test artifacts"
echo ""
echo "💡 Optional cleanup (run manually if needed):"
echo "  pnpm store prune  # Remove unreferenced packages from pnpm cache"
echo "  rm -rf node_modules && pnpm install  # Fresh dependency install"
echo ""
